from __future__ import annotations

from typing import List, Dict, Optional, Sequence
from pathlib import Path
import re

from .base import (
    FeaturePreset,
    FeaturePackage,
    MoveWizardSpec,
    _wrap,
    _spec,
    _pack_from_specs,
    _simple_pose_state,
    _simple_pose_air,
    _command_block,
    _state_minus_one,
    get_preset,
)


def _v26_doc_text(fid: str, title: str) -> str:
    return f"""# {title}

Generated by MugenForge Studio Factory Ultra.

## Purpose

This guide is for creators who do not want to hand-code M.U.G.E.N files. Use it as a decision sheet: pick the creative answer, then let MugenForge generate or repair the code/assets behind the scenes.

## Creator choices

- What should the player feel?
- What should the move/effect/sound communicate?
- Is it beginner-friendly, flashy, technical, defensive, boss-like, or goofy?
- What placeholder should be replaced first?

## Tool-handled work

- CMD/CNS/AIR scaffolding.
- Placeholder sprite and sound banks.
- Asset QA reports.
- Balance CSVs.
- Release readiness reports.
- Backup snapshots before risky edits.

## Related Feature Bank ID

`{fid}`
"""


def _v26_docs_package(feature_id: str, preset: FeaturePreset) -> FeaturePackage:
    safe = re.sub(r"[^A-Za-z0-9_\-]+", "_", feature_id).upper()
    return FeaturePackage(
        feature_id=feature_id,
        name=preset.name,
        extra_files={f"docs/FACTORY_ULTRA_{safe}.md": _v26_doc_text(feature_id, preset.name)},
        summary=f"Writes a Factory Ultra beginner guide: {preset.name}.",
        notes=["Documentation-only preset. No coding required."],
    )


def _v26_system_block(feature_id: str, title: str) -> str:
    seed = abs(sum(ord(c) for c in feature_id))
    var_a = 100 + (seed % 40)
    var_b = 140 + (seed % 40)
    return f"""; MugenForge Factory Ultra system scaffold: {title}
; Feature id: {feature_id}
; This block is intentionally centralized and readable so a non-coder can turn it on/off later.
[State -2, Ultra {title} flag]
type = VarSet
trigger1 = RoundState = 2
v = {var_a}
value = Var({var_a})
ignorehitpause = 1

[State -2, Ultra {title} timer]
type = VarAdd
trigger1 = Var({var_b}) > 0
v = {var_b}
value = -1
ignorehitpause = 1

[State -2, Ultra {title} debug]
type = AppendToClipboard
trigger1 = 0 ; set to 1 while tuning {title}
text = "\\nUltra {title}: flag=%d timer=%d"
params = Var({var_a}), Var({var_b})
ignorehitpause = 1

; Beginner tuning notes:
; - The Feature Bank installed the hook. You still choose sprites, sounds, timing, and feel.
; - Use Factory Ultra reports before release.
"""


def _v26_cmd_hook(feature_id: str, title: str) -> str:
    cmd_name = feature_id.replace("ultra_", "u_")[:28]
    return f"""[Command]
name = "{cmd_name}"
command = x+y
buffer.time = 4
time = 12

; Optional Factory Ultra command hook for {title}.
"""


def _v26_system_package(feature_id: str, preset: FeaturePreset) -> FeaturePackage:
    cmd = _v26_cmd_hook(feature_id, preset.name) if "cmd" in preset.blocks else ""
    cns = _v26_system_block(feature_id, preset.name) if "cns" in preset.blocks else ""
    air = _simple_pose_air(9400 + (abs(sum(ord(c) for c in feature_id)) % 500), preset.name, 5) if "air" in preset.blocks else ""
    return FeaturePackage(
        feature_id=feature_id,
        name=preset.name,
        cmd_block=_wrap(feature_id, preset.name, cmd),
        cns_block=_wrap(feature_id, preset.name, cns),
        air_block=_wrap(feature_id, preset.name, air),
        summary=f"Adds Factory Ultra no-code hook: {preset.name}.",
        notes=["Safe starter hook. Use the Creator Cockpit, Task Board, and reports to tune without hand-coding."],
    )


# Creator AutoPilot builders

_V26_MOVE_SPECS: Dict[str, MoveWizardSpec] = {
    "v26_assisted_light_chain": _spec("Assisted Light Chain", "v26_light_chain", "x, x", 1420, damage=32, frame_count=5, hit_frame=2, hit_box=(15, -70, 55, -35), sound=(5, 0), ground_velocity=(-3, 0)),
    "v26_assisted_launch_chain": _spec("Assisted Launch Chain", "v26_launch_chain", "x, y", 1425, damage=62, frame_count=7, hit_frame=3, hit_box=(8, -104, 62, -20), sound=(5, 2), ground_velocity=(-3, -6), air_velocity=(-3, -8)),
    "v26_simple_punish_button": _spec("Simple Punish Button", "v26_punish", "z", 1430, damage=78, frame_count=8, hit_frame=4, hit_box=(18, -80, 82, -28), sound=(5, 2), ground_velocity=(-6, 0)),
    "v26_beginner_anti_air": _spec("Beginner Anti Air", "v26_anti_air", "y", 1435, damage=68, frame_count=7, hit_frame=3, hit_box=(4, -112, 58, -24), sound=(5, 2), ground_velocity=(-2, -5), air_velocity=(-2, -7)),
    "v26_safe_fireball": _spec("Safe Test Fireball", "v26_safe_fireball", "~D, DF, F, x", 1440, move_type="projectile", damage=48, frame_count=7, hit_frame=4, hit_box=(22, -72, 80, -32), sound=(5, 3), ground_velocity=(-3, 0)),
    "v26_escape_special": _spec("Escape Special", "v26_escape", "B, D, DB, a", 1445, damage=38, frame_count=8, hit_frame=5, hit_box=(12, -70, 58, -26), sound=(5, 4), ground_velocity=(-2, 0)),
    "v26_showoff_taunt": _spec("Showoff Taunt", "v26_showoff", "s", 1450, move_type="movement", damage=0, frame_count=9, hit_frame=99, hit_box=(0, 0, 0, 0), sound=(5, 0), ground_velocity=(0, 0)),
    "v26_training_super": _spec("Training Super", "v26_training_super", "~D, DF, F, D, DF, F, x", 3500, damage=190, frame_count=12, hit_frame=6, hit_box=(16, -90, 140, -16), sound=(5, 6), ground_velocity=(-7, -3)),
    "v26_boss_phase_attack": _spec("Boss Phase Attack", "v26_boss_phase", "~D, DB, B, D, DF, F, z", 3600, move_type="projectile", damage=230, frame_count=14, hit_frame=7, hit_box=(-20, -120, 210, 0), sound=(5, 7), ground_velocity=(-8, -4)),
    "v26_signature_finisher": _spec("Signature Finisher", "v26_finisher", "~D, DF, F, D, DB, B, c", 3700, damage=260, frame_count=15, hit_frame=8, hit_box=(8, -112, 160, -10), sound=(5, 7), ground_velocity=(-9, -5)),
}


def _v26_doc_package(feature_id: str, preset: FeaturePreset) -> FeaturePackage:
    safe = re.sub(r"[^A-Za-z0-9_\-]+", "_", feature_id).upper()
    rel = f"docs/CREATOR_AUTOPILOT_{safe}.md"
    text = f"""# {preset.name}

Generated by MugenForge Studio Creator AutoPilot.

## What this is

{preset.description}

## No-code workflow

1. Pick the creative direction.
2. Let MugenForge generate safe starter scaffolding and reports.
3. Replace placeholder art and sound.
4. Use Animation Player and CLSN Editor for timing/hitboxes.
5. Test in M.U.G.E.N and run Final QA.

## Creator choices

- Visual style
- Sound/voice style
- Animation timing
- Hitbox feel
- Balance and personality

## Related feature id

`{feature_id}`
"""
    return FeaturePackage(feature_id=feature_id, name=preset.name, extra_files={rel: text}, summary=f"Writes Creator AutoPilot guide: {preset.name}.", notes=["Documentation helper; no hand coding required."])


def _v26_autopilot_system_package(feature_id: str, preset: FeaturePreset) -> FeaturePackage:
    seed = abs(sum(ord(c) for c in feature_id))
    var_no = 40 + (seed % 19)
    cmd_name = feature_id.replace("v26_", "")[:28]
    cmd = ""
    if "cmd" in preset.blocks:
        cmd = f"""[Command]
name = "{cmd_name}"
command = x+y
; Change this command later in the Code Assistant if needed.
time = 12
buffer.time = 4
"""
    cns = ""
    if "cns" in preset.blocks:
        cns = f"""; Creator AutoPilot system hook: {preset.name}
; Feature id: {feature_id}
[State -2, Creator AutoPilot {preset.name} flag]
type = VarSet
trigger1 = RoundState >= 0
v = {var_no}
value = Var({var_no})
ignorehitpause = 1

[State -2, Creator AutoPilot {preset.name} note]
type = AppendToClipboard
trigger1 = 0 ; set to 1 while tuning this helper
text = "\\nCreator AutoPilot: {preset.name} var{var_no}=%d"
params = Var({var_no})
ignorehitpause = 1

; Beginner note: this is a central hook/router. Use the Creator AutoPilot tab, Move Wizard, and Feature Bank to add real moves around it.
"""
    air = _simple_pose_air(9300 + (seed % 600), preset.name, 5) if "air" in preset.blocks else ""
    return FeaturePackage(
        feature_id=feature_id,
        name=preset.name,
        cmd_block=_wrap(feature_id, preset.name, cmd),
        cns_block=_wrap(feature_id, preset.name, cns),
        air_block=_wrap(feature_id, preset.name, air),
        summary=f"Adds Creator AutoPilot scaffold: {preset.name}.",
        notes=["Designed as no-code routing/scaffolding, not a finished balance solution."],
    )


# Factory Ultra compatibility patches

def _factory_ultra_compat_doc(feature_id: str, preset: FeaturePreset) -> FeaturePackage:
    safe = re.sub(r"[^A-Za-z0-9_\-]+", "_", feature_id).upper()
    text = f"""# {preset.name}

Generated by MugenForge Studio Factory Ultra.

## Purpose

{preset.description}

## Beginner workflow

- Make the creative decision first.
- Let MugenForge generate code, reports, and placeholder assets.
- Replace placeholder art/sound.
- Use Animation Player and CLSN Editor for visual tuning.
- Run Factory Ultra reports before release.

Feature ID: `{feature_id}`
"""
    return FeaturePackage(feature_id=feature_id, name=preset.name, extra_files={f"docs/FACTORY_ULTRA_{safe}.md": text}, summary=f"Writes Factory Ultra guide: {preset.name}.", notes=["No-code documentation helper."])


def _factory_ultra_compat_system(feature_id: str, preset: FeaturePreset) -> FeaturePackage:
    seed = abs(sum(ord(c) for c in feature_id))
    var_no = 100 + (seed % 40)
    cmd = ""
    if "cmd" in preset.blocks:
        cmd_name = feature_id[:28]
        cmd = f"""[Command]
name = "{cmd_name}"
command = x+y
time = 12
buffer.time = 4
"""
    cns = ""
    if "cns" in preset.blocks:
        cns = f"""; Factory Ultra no-code system hook: {preset.name}
; Feature id: {feature_id}
[State -2, Factory Ultra {preset.name} flag]
type = VarSet
trigger1 = RoundState >= 0
v = {var_no}
value = Var({var_no})
ignorehitpause = 1

[State -2, Factory Ultra {preset.name} debug]
type = AppendToClipboard
trigger1 = 0 ; set to 1 while tuning this feature
text = "\\nFactory Ultra: {preset.name} var{var_no}=%d"
params = Var({var_no})
ignorehitpause = 1
"""
    air = _simple_pose_air(9600 + (seed % 300), preset.name, 5) if "air" in preset.blocks else ""
    return FeaturePackage(feature_id=feature_id, name=preset.name, cmd_block=_wrap(feature_id, preset.name, cmd), cns_block=_wrap(feature_id, preset.name, cns), air_block=_wrap(feature_id, preset.name, air), summary=f"Adds Factory Ultra no-code scaffold: {preset.name}.", notes=["Safe starter hook; use visual reports to tune."])


def _factory_ultra_compat_move(feature_id: str, preset: FeaturePreset) -> FeaturePackage:
    seed = abs(sum(ord(c) for c in feature_id))
    state_no = 4300 + (seed % 1200)
    name = preset.name
    lname = (preset.name + " " + feature_id).lower()
    command = "x"
    if "fireball" in lname or "orb" in lname or "projectile" in lname:
        command = "~D, DF, F, x"
    elif "super" in lname or "finisher" in lname:
        command = "~D, DF, F, D, DF, F, z"
    elif "dash" in lname or "carry" in lname:
        command = "F, F, y"
    elif "anti" in lname or "launcher" in lname:
        command = "D, y"
    elif "guard" in lname or "breaker" in lname:
        command = "F, z"
    damage = 35 + (seed % 80)
    if "super" in lname or "finisher" in lname or "boss" in lname:
        damage += 120
    move_type = "projectile" if any(w in lname for w in ["fireball", "orb", "projectile", "screen control"]) else "attack"
    spec = _spec(name, feature_id[:28], command, state_no, damage=damage, frame_count=6 + (seed % 6), hit_frame=2 + (seed % 4), hit_box=(16, -84, 70 + (seed % 50), -18), sound=(5, seed % 8), ground_velocity=(-(3 + seed % 6), 0), air_velocity=(-3, -(4 + seed % 5)), move_type=move_type)
    pkg = _pack_from_specs(feature_id, preset.name, [spec], list(preset.beginner_notes))
    pkg.notes.append("Factory Ultra generated fallback move scaffold. Tune timing/hitboxes visually after install.")
    return pkg


def build_v26_feature(feature_id: str) -> Optional[FeaturePackage]:
    # 1. Compatibility fallback for any ultra_ prefix (always matches in legacy due to redefinition shadowing)
    if feature_id.startswith("ultra_"):
        preset = get_preset(feature_id)
        if "docs" in preset.blocks:
            return _factory_ultra_compat_doc(feature_id, preset)
        if {"cmd", "cns", "air"}.intersection(set(preset.blocks)) == {"cmd", "cns", "air"} or ("cmd" in preset.blocks and "air" in preset.blocks):
            return _factory_ultra_compat_move(feature_id, preset)
        return _factory_ultra_compat_system(feature_id, preset)

    # v2.6 (Creator AutoPilot) feature list
    v26_pilot_ids = {
        "v26_character_dna_docs", "v26_creator_dashboard_docs", "v26_time_machine_docs", "v26_asset_library_docs", "v26_move_lab_docs",
        "v26_combo_tree_docs", "v26_art_task_board_docs", "v26_beginner_tuning_docs", "v26_training_pack_docs", "v26_final_qa_docs",
        "v26_no_code_pipeline_docs", "v26_tuning_panel_router", "v26_damage_knob_router", "v26_hitpause_knob_router", "v26_pushback_knob_router",
        "v26_input_buffer_router", "v26_auto_combo_assist_router", "v26_beginner_cancel_helper", "v26_state_safety_net", "v26_auto_return_idle_guard",
        "v26_meter_display_hook", "v26_combo_counter_hook", "v26_hitbox_review_overlay", "v26_training_todo_clipboard", "v26_asset_missing_warning",
        "v26_palette_style_router", "v26_sound_call_router", "v26_assisted_light_chain", "v26_assisted_launch_chain", "v26_simple_punish_button",
        "v26_beginner_anti_air", "v26_safe_fireball", "v26_escape_special", "v26_showoff_taunt", "v26_training_super", "v26_boss_phase_attack",
        "v26_signature_finisher", "v26_ai_style_director", "v26_accessibility_fx_limiter", "v26_round_start_director", "v26_accessible_creator_docs"
    }

    # 2. Handle Creator AutoPilot features
    if feature_id in v26_pilot_ids:
        preset = get_preset(feature_id)
        if feature_id.endswith("_docs") or feature_id == "v26_character_dna_docs":
            return _v26_doc_package(feature_id, preset)
        if feature_id in _V26_MOVE_SPECS:
            pkg = _pack_from_specs(feature_id, preset.name, [_V26_MOVE_SPECS[feature_id]], list(preset.beginner_notes))
            pkg.notes.append("Creator AutoPilot move: use Move Lab, Animation Player, and CLSN Editor after installing.")
            return pkg
        return _v26_autopilot_system_package(feature_id, preset)

    return None
