from __future__ import annotations

from typing import List, Dict, Optional, Sequence
from pathlib import Path
import re
import json

from .base import (
    FeaturePreset,
    FeaturePackage,
    MoveWizardSpec,
    _wrap,
    _spec,
    _pack_from_specs,
    _simple_pose_state,
    _simple_pose_air,
    _state_minus_one,
    _command_block,
    get_preset,
)
from ..parsers import COMMON_ANIMS


def _v23_doc_text(title: str, feature_id: str) -> str:
    return f"""# {title}

Generated by MugenForge Studio FF+.

This file exists so the creator can make decisions without editing M.U.G.E.N code by hand.

## What to fill in

- What should this feature look/sound like?
- Which animation action numbers does it use?
- Which sound group/index does it use?
- Is the move safe, unsafe, armored, projectile-based, or throw-based?
- What should be checked in Animation Player and CLSN Editor?

## Beginner rule

Do the fun part here: naming, feel, visuals, sound, timing notes. Let Feature Bank / Move Wizard write the raw CMD, CNS, and AIR blocks.

Feature Bank ID: `{feature_id}`
"""


def _v23_docs_package(feature_id: str, preset: FeaturePreset) -> FeaturePackage:
    filename = {
        "color_palette_manager_docs": "docs/PALETTE_MANAGER_GUIDE.md",
        "sprite_axis_audit_docs": "docs/SPRITE_AXIS_AUDIT.md",
        "release_package_audit_docs": "docs/RELEASE_PACKAGE_AUDIT.md",
        "character_bible_docs": "docs/CHARACTER_BIBLE.md",
        "combo_recipe_docs": "testing/combo_trials/COMBO_RECIPES.md",
        "balance_worksheet_docs": "docs/BALANCE_WORKSHEET.md",
        "test_plan_docs": "testing/TEST_PLAN.md",
        "accessibility_notes_docs": "docs/ACCESSIBILITY_NOTES.md",
        "readme_generator_docs": "README_RELEASE_TEMPLATE.md",
        "credits_license_docs": "CREDITS_AND_PERMISSIONS.md",
        "win_quote_bank": "docs/WIN_QUOTES.md",
    }.get(feature_id, f"docs/{feature_id.upper()}.md")
    return FeaturePackage(
        feature_id=feature_id,
        name=preset.name,
        extra_files={filename: _v23_doc_text(preset.name, feature_id)},
        summary=f"Writes {preset.name} planning/documentation file. No code editing required.",
        notes=["This is a planning/doc preset, not a combat code block."],
    )


def _v23_required_air(feature_id: str, preset: FeaturePreset) -> FeaturePackage:
    if feature_id == "required_action_library":
        action_ids = [0, 5, 10, 11, 12, 20, 21, 40, 41, 42, 47, 100, 105, 120, 130, 140, 150, 170, 180, 190, 195]
        air = "".join(_simple_pose_air(n, COMMON_ANIMS.get(n, f"Action {n}"), 4 if n < 5000 else 5) for n in action_ids)
        summary = "Adds beginner-safe placeholders for many common required/round-flow actions. Replace art later."
    elif feature_id == "complete_gethit_library":
        action_ids = [5000, 5010, 5020, 5030, 5050, 5060, 5070, 5080, 5100, 5110, 5150]
        air = "".join(_simple_pose_air(n, COMMON_ANIMS.get(n, f"Get-hit {n}"), 5) for n in action_ids)
        summary = "Adds placeholder get-hit/fall/recovery/dead action library."
    else:
        action_ids = [7000, 7001, 7010, 7011, 7020, 7021, 7030, 7040, 7050, 7060, 7070, 7080]
        labels = ["Small Hitspark", "Big Hitspark", "Guard Spark", "Super Spark", "Dust Puff", "Landing Dust", "Slash FX", "Aura Loop", "Projectile Core", "Throw FX", "Cancel Spark", "Clash Spark"]
        air = "".join(_simple_pose_air(n, label, 4) for n, label in zip(action_ids, labels))
        summary = "Adds visual template actions for sparks, dust, projectile, aura, throw, cancel, and clash effects."
    return FeaturePackage(feature_id, preset.name, air_block=_wrap(feature_id, preset.name, air), summary=summary)


def _v23_state2_block(feature_id: str, title: str, var_no: int, lines: str) -> str:
    return f"""; MugenForge FF+ {title}
; This block is intentionally readable and conservative.
; Tune it after in-game testing.
[State -2, FF+ {title} init]
type = VarSet
trigger1 = RoundState < 2
v = {var_no}
value = 0
ignorehitpause = 1

{lines.rstrip()}

"""


def _v23_system_package(feature_id: str, preset: FeaturePreset) -> FeaturePackage:
    title = preset.name
    var_seed = 50 + (sum(ord(ch) for ch in feature_id) % 45)
    cmd = ""
    air = ""
    notes: List[str] = ["Generated as a beginner-readable system skeleton. It is safe to install, but final tuning still needs in-game testing."]

    if feature_id in {"throw_tech_system", "burst_escape_system", "roman_cancel_system", "tag_assist_placeholder"}:
        command = {
            "throw_tech_system": "x+y",
            "burst_escape_system": "x+y+z",
            "roman_cancel_system": "y+z",
            "tag_assist_placeholder": "a+b",
        }[feature_id]
        state_no = {
            "throw_tech_system": 6400,
            "burst_escape_system": 6410,
            "roman_cancel_system": 6420,
            "tag_assist_placeholder": 6430,
        }[feature_id]
        cmd = _command_block(feature_id, command, 8) + _state_minus_one(feature_id, state_no, title)
        cns = f"""; MugenForge FF+ {title}
[Statedef {state_no}]
type = S
movetype = I
physics = S
anim = {state_no}
ctrl = 0
sprpriority = 5

[State {state_no}, spend/read variables]
type = VarAdd
trigger1 = Time = 0
v = {var_seed}
value = 1

[State {state_no}, visual feedback]
type = PalFX
trigger1 = Time = 0
time = 12
add = 60,60,90
mul = 220,220,255

[State {state_no}, end]
type = ChangeState
trigger1 = Time >= 18
value = 0
ctrl = 1

"""
        air = _simple_pose_air(state_no, title, 5)
        return FeaturePackage(feature_id, title, _wrap(feature_id, title, cmd), _wrap(feature_id, title, cns), _wrap(feature_id, title, air), summary=f"Adds no-code starter command/state for {title}.", notes=notes)

    if feature_id in {"wall_bounce_system", "ground_bounce_system", "stun_meter_system", "clash_system", "round_intro_outro_director"}:
        state_no = {
            "wall_bounce_system": 6500,
            "ground_bounce_system": 6510,
            "stun_meter_system": 6520,
            "clash_system": 6530,
            "round_intro_outro_director": 6540,
        }[feature_id]
        cns = f"""; MugenForge FF+ {title}
; Use this as a named destination/state idea. Wire specific moves into it after testing.
[Statedef {state_no}]
type = S
movetype = I
physics = N
anim = {state_no}
ctrl = 0
sprpriority = 4

[State {state_no}, freeze/control]
type = VelSet
trigger1 = Time = 0
x = 0
y = 0

[State {state_no}, feedback]
type = EnvShake
trigger1 = Time = 0
time = 10
freq = 90
ampl = -3
ignorehitpause = 1

[State {state_no}, end]
type = ChangeState
trigger1 = Time >= 20
value = 0
ctrl = 1

"""
        air = _simple_pose_air(state_no, title, 5)
        return FeaturePackage(feature_id, title, cns_block=_wrap(feature_id, title, cns), air_block=_wrap(feature_id, title, air), summary=f"Adds placeholder state/action for {title}.", notes=notes)

    special_lines = {
        "smart_cancel_system": """[State -2, FF+ mark cancel window while attacking]\ntype = VarSet\ntriggerall = MoveType = A\ntrigger1 = AnimElemNo(0) >= 2\nv = 50\nvalue = 1\nignorehitpause = 1\n\n[State -2, FF+ clear cancel window]\ntype = VarSet\ntrigger1 = MoveType != A\nv = 50\nvalue = 0\nignorehitpause = 1""",
        "chain_cancel_system": """[State -2, FF+ chain route note]\ntype = DisplayToClipboard\ntrigger1 = Var(50) = 1\ntext = \"Chain window open: light -> medium -> heavy\"\nignorehitpause = 1""",
        "jump_cancel_system": """[State -2, FF+ jump cancel marker]\ntype = VarSet\ntrigger1 = MoveHit\ntrigger1 = StateType != A\nv = 51\nvalue = 1\nignorehitpause = 1""",
        "dash_cancel_system": """[State -2, FF+ dash cancel marker]\ntype = VarSet\ntrigger1 = MoveContact\ntrigger1 = Power >= 250\nv = 52\nvalue = 1\nignorehitpause = 1""",
        "super_cancel_system": """[State -2, FF+ super cancel marker]\ntype = VarSet\ntrigger1 = MoveContact\ntrigger1 = Power >= 1000\nv = 53\nvalue = 1\nignorehitpause = 1""",
        "ex_meter_spender": """[State -2, FF+ EX meter note]\ntype = DisplayToClipboard\ntrigger1 = Power >= 500\ntrigger1 = 0 ; change to your EX move trigger\ntext = \"EX ready: spend 500 power in the move state\"\nignorehitpause = 1""",
        "meter_gain_system": """[State -2, FF+ tiny meter reward example]\ntype = PowerAdd\ntrigger1 = MoveContact\ntrigger1 = Time % 12 = 0\nvalue = 5\nignorehitpause = 1""",
        "combo_scaling_system": """[State -2, FF+ combo scaling variable]\ntype = VarSet\ntrigger1 = NumEnemy > 0\ntrigger1 = P2MoveType = H\nv = 54\nvalue = HitCount\nignorehitpause = 1""",
        "juggle_limiter": """[State -2, FF+ juggle count idea]\ntype = VarAdd\ntrigger1 = MoveHit\ntrigger1 = P2StateType = A\nv = 55\nvalue = 1\nignorehitpause = 1""",
        "otg_limiter": """[State -2, FF+ OTG count idea]\ntype = VarAdd\ntrigger1 = MoveHit\ntrigger1 = P2StateType = L\nv = 56\nvalue = 1\nignorehitpause = 1""",
        "hit_pause_bank": """; HitDef pausetime examples:\n; light pausetime = 4,6\n; medium pausetime = 6,8\n; heavy pausetime = 9,12\n; super pausetime = 12,18\n[State -2, FF+ hitpause note]\ntype = Null\ntrigger1 = 1""",
        "hitstun_tuning_bank": """; HitDef hittime examples:\n; light ground.hittime = 10\n; medium ground.hittime = 14\n; heavy ground.hittime = 18\n; launcher air.hittime = 24\n[State -2, FF+ hitstun note]\ntype = Null\ntrigger1 = 1""",
        "guardstun_tuning_bank": """; HitDef guardtime examples:\n; unsafe light guard.hittime = 8\n; safe special guard.hittime = 16\n; plus-frame super guard.hittime = 24\n[State -2, FF+ guardstun note]\ntype = Null\ntrigger1 = 1""",
        "training_input_display": """[State -2, FF+ input display]\ntype = DisplayToClipboard\ntrigger1 = 1\ntext = \"cmd/debug state=%d anim=%d time=%d ctrl=%d power=%d\"\nparams = stateno, anim, time, ctrl, power\nignorehitpause = 1""",
        "training_damage_readout": """[State -2, FF+ damage readout]\ntype = AppendToClipboard\ntrigger1 = 1\ntext = \"\\nlife=%d p2life=%d hitcount=%d\"\nparams = life, enemynear,life, hitcount\nignorehitpause = 1""",
        "training_frame_data_readout": """[State -2, FF+ frame data readout]\ntype = AppendToClipboard\ntrigger1 = 1\ntext = \"\\nframe data: stateno=%d time=%d animelem=%d movetype=%s\"\nparams = stateno, time, animelemno(0), movetype\nignorehitpause = 1""",
        "training_hitbox_toggle": """[State -2, FF+ CLSN note]\ntype = DisplayToClipboard\ntrigger1 = 0 ; set to 1 while tuning CLSN in-game\ntext = \"Use MugenForge CLSN Editor for visual hitbox edits, then save AIR with backup.\"\nignorehitpause = 1""",
        "training_dummy_guard_mode": """[State -2, FF+ training dummy guard notes]\ntype = Null\ntrigger1 = 1\n; Add engine-specific dummy behavior here if your M.U.G.E.N build supports it.""",
        "ai_personality_router": """[State -2, FF+ AI personality]\ntype = VarSet\ntrigger1 = AILevel > 0\ntrigger1 = RoundState = 2\nv = 60\nvalue = 1 ; 1=rushdown, 2=zoner, 3=grappler, 4=boss\nignorehitpause = 1""",
        "ai_range_router": """[State -2, FF+ AI range idea]\ntype = ChangeState\ntriggerall = AILevel > 0\ntriggerall = ctrl\ntrigger1 = P2BodyDist X > 120\ntrigger1 = Random < 20\nvalue = 1000""",
        "ai_combo_router": """[State -2, FF+ AI combo follow-up idea]\ntype = ChangeState\ntriggerall = AILevel > 0\ntrigger1 = MoveHit\ntrigger1 = Random < 35\nvalue = 210""",
        "ai_anti_air_router": """[State -2, FF+ AI anti-air idea]\ntype = ChangeState\ntriggerall = AILevel > 0\ntriggerall = ctrl\ntrigger1 = P2StateType = A\ntrigger1 = P2BodyDist X < 70\nvalue = 1100""",
        "ai_escape_router": """[State -2, FF+ AI escape idea]\ntype = ChangeState\ntriggerall = AILevel > 0\ntriggerall = ctrl\ntrigger1 = P2BodyDist X < 30\ntrigger1 = Random < 25\nvalue = 105""",
        "parry_reward_system": """[State -2, FF+ parry reward idea]\ntype = PowerAdd\ntrigger1 = Var(61) = 1\nvalue = 100\nignorehitpause = 1""",
        "perfect_guard_system": """[State -2, FF+ perfect guard marker]\ntype = VarSet\ntrigger1 = StateType != A\ntrigger1 = MoveType = H\ntrigger1 = Time < 4\nv = 62\nvalue = 1\nignorehitpause = 1""",
        "guard_break_meter": """[State -2, FF+ guard meter idea]\ntype = VarAdd\ntrigger1 = MoveType = H\ntrigger1 = StateType != A\nv = 63\nvalue = 1\nignorehitpause = 1""",
        "armor_system": """[State -2, FF+ armor window example]\ntype = NotHitBy\ntrigger1 = Var(64) > 0\nvalue = SCA\nignorehitpause = 1""",
        "invuln_startup_bank": """; Copy into a state that needs invulnerable startup.\n[State -2, FF+ invuln startup note]\ntype = NotHitBy\ntrigger1 = 0 ; change to Time < N inside target state\nvalue = SCA\nignorehitpause = 1""",
        "projectile_priority_bank": """; Projectile tuning examples:\n; projpriority = 1 light, 3 medium, 5 super\n; velocity should match recovery so zoners are fair.\n[State -2, FF+ projectile priority note]\ntype = Null\ntrigger1 = 1""",
        "projectile_reflect_router": """[State -2, FF+ reflect hook note]\ntype = Null\ntrigger1 = 1\n; Wire reflect/absorb moves here after testing ReversalDef behavior.""",
        "assist_cooldown_system": """[State -2, FF+ assist cooldown]\ntype = VarAdd\ntrigger1 = Var(70) > 0\nv = 70\nvalue = -1\nignorehitpause = 1""",
        "install_timer_hud": """[State -2, FF+ install timer HUD]\ntype = AppendToClipboard\ntrigger1 = Var(71) > 0\ntext = \"\\nInstall timer=%d\"\nparams = Var(71)\nignorehitpause = 1""",
        "boss_phase_router": """[State -2, FF+ boss phase]\ntype = VarSet\ntrigger1 = Life < LifeMax / 2\nv = 72\nvalue = 2\nignorehitpause = 1""",
        "move_unlock_flags": """[State -2, FF+ move unlock flags]\ntype = VarSet\ntrigger1 = RoundNo >= 1\nv = 73\nvalue = 1\nignorehitpause = 1""",
        "screen_shake_router": """[State -2, FF+ screen shake example]\ntype = EnvShake\ntrigger1 = 0 ; copy this into big-impact states\ntime = 12\nfreq = 90\nampl = -4\nignorehitpause = 1""",
        "camera_focus_router": """[State -2, FF+ cinematic camera note]\ntype = ScreenBound\ntrigger1 = 0 ; copy into cinematic states\nvalue = 0\nmovecamera = 0,0\nignorehitpause = 1""",
        "palfx_impact_bank": """[State -2, FF+ PalFX impact example]\ntype = PalFX\ntrigger1 = 0 ; copy into impact states\ntime = 8\nadd = 80,80,80\nmul = 256,256,256\nignorehitpause = 1""",
        "afterimage_polish_bank": """[State -2, FF+ AfterImage example]\ntype = AfterImage\ntrigger1 = 0 ; copy into dash/super states\ntime = 16\nlength = 8\npalcontrast = 140,140,220\nignorehitpause = 1""",
        "sound_router": """[State -2, FF+ sound router notes]\ntype = Null\ntrigger1 = 1\n; Suggested groups: 0 system, 5 attacks, 6 specials, 7 supers, 10 voice.""",
        "voice_router": """[State -2, FF+ voice router notes]\ntype = Null\ntrigger1 = 1\n; Use PlaySnd group 10 for voice so it stays separate from hits and movement.""",
    }
    if feature_id in {"hitspark_router", "guard_spark_router", "step_dust_router", "landing_dust_router"}:
        action_map = {
            "hitspark_router": (7000, "Hitspark Router", "sparkxy = -10,-60"),
            "guard_spark_router": (7010, "Guard Spark Router", "sparkxy = -8,-58"),
            "step_dust_router": (7020, "Step Dust Router", "pos = 0,0"),
            "landing_dust_router": (7021, "Landing Dust Router", "pos = 0,0"),
        }
        anim_no, label, pos_line = action_map[feature_id]
        cns = f"""; MugenForge FF+ {label}
[State -2, {label} note]
type = Null
trigger1 = 1
; Copy this Explod into the states that need it.
; type = Explod
; anim = {anim_no}
; {pos_line}
; postype = p1
; sprpriority = 5
; ownpal = 1
"""
        air = _simple_pose_air(anim_no, label, 4)
        return FeaturePackage(feature_id, title, cns_block=_wrap(feature_id, title, cns), air_block=_wrap(feature_id, title, air), summary=f"Adds {label} placeholder action and routing notes.", notes=notes)

    lines = special_lines.get(feature_id)
    if lines is None:
        lines = f"""[State -2, FF+ {title} note]\ntype = Null\ntrigger1 = 1\n; Starter hook for {title}. Use this as the central code bank location."""
    cns = _v23_state2_block(feature_id, title, var_seed, lines)
    return FeaturePackage(feature_id, title, cns_block=_wrap(feature_id, title, cns), summary=f"Adds FF+ no-code system skeleton: {title}.", notes=notes)


# v2.5 Factory Max builders

_V25_DOC_IDS = {
    "max_sprite_organizer_docs", "max_image_editor_macros_docs", "max_offset_viewer_docs", "max_throw_creator_docs",
    "max_bg_stage_editor_docs", "max_storyboard_editor_docs", "max_import_resolver_docs", "max_palette_link_audit_docs",
    "max_onion_skin_docs", "max_frame_interpolation_docs", "max_sound_viewer_docs", "max_autocomplete_bank_docs",
    "max_code_history_safety_docs", "max_debugger_docs", "max_frame_data_export_docs", "max_combo_trial_docs",
    "max_release_qa_docs", "max_accessibility_docs"
}

_V25_MOVE_SPECS: Dict[str, MoveWizardSpec] = {
    "max_target_combo": _spec("Target Combo", "max_target_combo", "x, y", 1260, damage=45, frame_count=6, hit_frame=3, hit_box=(18, -76, 68, -34), sound=(5, 1), ground_velocity=(-4, 0)),
    "max_chain_uppercut": _spec("Chain Uppercut", "max_chain_uppercut", "F, y", 1265, damage=70, frame_count=7, hit_frame=3, hit_box=(10, -100, 58, -22), sound=(5, 2), ground_velocity=(-3, -6), air_velocity=(-3, -8)),
    "max_rekka_finish_low": _spec("Rekka Finish Low", "max_rekka_low", "~D, DF, F, a", 1270, damage=65, frame_count=7, hit_frame=4, hit_box=(18, -36, 84, -8), body_box=(-20, -70, 20, 0), sound=(5, 2), ground_velocity=(-6, 0)),
    "max_rekka_finish_overhead": _spec("Rekka Finish Overhead", "max_rekka_overhead", "~D, DF, F, b", 1271, damage=72, frame_count=8, hit_frame=5, hit_box=(18, -92, 78, -42), sound=(5, 2), ground_velocity=(-5, 0)),
    "max_flame_uppercut": _spec("Flame Uppercut", "max_flame_uppercut", "~F, D, DF, z", 1280, damage=95, frame_count=8, hit_frame=3, hit_box=(8, -108, 60, -18), sound=(5, 4), ground_velocity=(-4, -8), air_velocity=(-4, -9)),
    "max_ice_projectile": _spec("Ice Projectile", "max_ice_projectile", "~D, DF, F, y", 1285, move_type="projectile", damage=60, frame_count=7, hit_frame=4, hit_box=(24, -70, 78, -34), sound=(5, 3), ground_velocity=(-4, 0)),
    "max_lightning_dash": _spec("Lightning Dash", "max_lightning_dash", "F, F, z", 1290, damage=80, frame_count=7, hit_frame=3, hit_box=(18, -76, 100, -22), sound=(5, 4), ground_velocity=(-7, 0)),
    "max_ground_pound": _spec("Ground Pound", "max_ground_pound", "D, D, z", 1295, damage=85, frame_count=9, hit_frame=5, hit_box=(-36, -26, 86, 4), sound=(5, 5), ground_velocity=(-4, -2)),
    "max_command_counter": _spec("Command Counter", "max_command_counter", "B, DB, D, x", 1300, damage=75, frame_count=8, hit_frame=5, hit_box=(14, -84, 64, -28), sound=(5, 4), ground_velocity=(-5, 0)),
    "max_air_special_dive": _spec("Air Special Dive", "max_air_dive", "D, DF, F, a", 1305, damage=70, frame_count=7, hit_frame=3, hit_box=(14, -64, 70, -8), body_box=(-18, -82, 18, 4), sound=(5, 3), ground_velocity=(-4, -3), air_velocity=(-3, 6)),
    "max_ex_uppercut": _spec("EX Uppercut", "max_ex_uppercut", "~F, D, DF, c", 1310, damage=115, frame_count=9, hit_frame=3, hit_box=(8, -112, 70, -18), sound=(5, 6), ground_velocity=(-5, -9), air_velocity=(-4, -10)),
    "max_ex_fireball": _spec("EX Fireball", "max_ex_fireball", "~D, DF, F, z", 1315, move_type="projectile", damage=85, frame_count=8, hit_frame=4, hit_box=(22, -76, 94, -30), sound=(5, 6), ground_velocity=(-6, 0)),
    "max_level2_super": _spec("Level 2 Super", "max_level2_super", "~D, DF, F, D, DF, F, y", 3200, move_type="projectile", damage=210, frame_count=12, hit_frame=6, hit_box=(20, -86, 160, -20), sound=(5, 6), ground_velocity=(-8, 0)),
    "max_cinematic_finisher": _spec("Cinematic Finisher", "max_cinematic_finisher", "~D, DB, B, D, DB, B, z", 3300, damage=260, frame_count=14, hit_frame=7, hit_box=(10, -100, 110, -10), sound=(5, 7), ground_velocity=(-9, -4), air_velocity=(-6, -8)),
    "max_boss_desperation": _spec("Boss Desperation", "max_boss_desperation", "~D, DF, F, D, DF, F, c", 3400, move_type="projectile", damage=320, frame_count=16, hit_frame=8, hit_box=(0, -120, 220, 0), sound=(5, 7), ground_velocity=(-10, -4)),
}


def _v25_doc_text(fid: str, title: str) -> str:
    return f"""# {title}

Generated by MugenForge Studio Factory Max.

## Goal

This page exists so a beginner can make the creative decision while MugenForge handles the ugly routing/code in the app.

## What to decide

- What should this feature look like?
- Which sprites/sounds should represent it?
- Is it fast, slow, safe, risky, flashy, simple, or boss-level?
- What should the player feel when using it?

## What MugenForge can handle

- CMD/CNS/AIR scaffolding from Feature Bank presets.
- Placeholder sprites/sounds.
- AIR action repair.
- SFF/SND starter rebuilds.
- Project reports, state maps, move lists, and release ZIPs.

## Manual fun part

- Replace placeholder art.
- Drag hitboxes in the CLSN editor.
- Test the move in-game.
- Adjust timing/damage until it feels right.

## Related feature id

`{fid}`
"""


def _v25_docs_package(feature_id: str, preset: FeaturePreset) -> FeaturePackage:
    safe = re.sub(r"[^A-Za-z0-9_\-]+", "_", feature_id).upper()
    rel = f"docs/FACTORY_MAX_{safe}.md"
    text = _v25_doc_text(feature_id, preset.name)
    return FeaturePackage(
        feature_id=feature_id,
        name=preset.name,
        extra_files={rel: text},
        summary=f"Writes a beginner-friendly Factory Max guide: {preset.name}.",
        notes=["No M.U.G.E.N code is required for this documentation helper."],
    )


def _v25_system_block(feature_id: str, title: str) -> str:
    var_seed = abs(sum(ord(c) for c in feature_id)) % 80
    var_a = 80 + (var_seed % 20)
    return f"""; MugenForge Factory Max system scaffold: {title}
; Feature id: {feature_id}
; This is intentionally readable and centralized so non-coders can toggle/tune the feature later.
[State -2, Factory Max {title} enable flag]
type = VarSet
trigger1 = RoundState = 2
v = {var_a}
value = Var({var_a})
ignorehitpause = 1

[State -2, Factory Max {title} debug note]
type = AppendToClipboard
trigger1 = 0 ; set to 1 while tuning {title}
text = "\\nFactory Max: {title} var{var_a}=%d"
params = Var({var_a})
ignorehitpause = 1

; Beginner tuning notes:
; - Keep this as a router/hook, then use Move Wizard or Feature Bank to add actual moves.
; - Do not delete the marker comments around this block unless you want MugenForge to reinstall it.
"""


def _v25_cmd_hook(feature_id: str, title: str) -> str:
    cmd_name = feature_id.replace("max_", "")[:28]
    return f"""[Command]
name = "{cmd_name}"
command = x+y
time = 12
buffer.time = 4

; Factory Max optional command hook for {title}.
; Wire this to a custom StateDef only after testing.
"""


def _v25_system_package(feature_id: str, preset: FeaturePreset) -> FeaturePackage:
    cmd = _v25_cmd_hook(feature_id, preset.name) if "cmd" in preset.blocks else ""
    cns = _v25_system_block(feature_id, preset.name) if "cns" in preset.blocks else ""
    air = _simple_pose_air(8900 + (abs(sum(ord(c) for c in feature_id)) % 700), preset.name, 5) if "air" in preset.blocks else ""
    return FeaturePackage(
        feature_id=feature_id,
        name=preset.name,
        cmd_block=_wrap(feature_id, preset.name, cmd),
        cns_block=_wrap(feature_id, preset.name, cns),
        air_block=_wrap(feature_id, preset.name, air),
        summary=f"Adds Factory Max no-code scaffold: {preset.name}.",
        notes=["This is a safe starter hook. Use the visual editors/reports to tune it instead of hand-coding from scratch."],
    )


def build_v23_v25_feature(feature_id: str) -> Optional[FeaturePackage]:
    # Set of v2.3 features
    v23_ids = {
        "required_action_library", "complete_gethit_library", "ffplus_air_template_bank",
        "smart_cancel_system", "chain_cancel_system", "jump_cancel_system", "dash_cancel_system",
        "super_cancel_system", "ex_meter_spender", "meter_gain_system", "combo_scaling_system",
        "juggle_limiter", "otg_limiter", "wall_bounce_system", "ground_bounce_system", "hitstun_tuning_bank",
        "guardstun_tuning_bank", "hit_pause_bank", "hitspark_router", "guard_spark_router", "sound_router",
        "voice_router", "step_dust_router", "landing_dust_router", "screen_shake_router", "camera_focus_router",
        "palfx_impact_bank", "afterimage_polish_bank", "training_hitbox_toggle", "training_input_display",
        "training_damage_readout", "training_frame_data_readout", "training_dummy_guard_mode", "ai_personality_router",
        "ai_range_router", "ai_combo_router", "ai_anti_air_router", "ai_escape_router", "throw_tech_system",
        "parry_reward_system", "perfect_guard_system", "guard_break_meter", "stun_meter_system", "burst_escape_system",
        "roman_cancel_system", "clash_system", "armor_system", "invuln_startup_bank", "projectile_priority_bank",
        "projectile_reflect_router", "assist_cooldown_system", "tag_assist_placeholder", "install_timer_hud",
        "boss_phase_router", "round_intro_outro_director", "win_quote_bank", "move_unlock_flags",
        "color_palette_manager_docs", "sprite_axis_audit_docs", "release_package_audit_docs", "character_bible_docs",
        "combo_recipe_docs", "balance_worksheet_docs", "test_plan_docs", "accessibility_notes_docs",
        "readme_generator_docs", "credits_license_docs"
    }

    # Set of v2.5 features
    v25_ids = _V25_DOC_IDS.union(set(_V25_MOVE_SPECS.keys())).union({
        "max_universal_chain_router", "max_air_chain_router", "max_cancel_window_hud", "max_meter_rules_router",
        "max_ex_move_router", "max_super_freeze_router", "max_proration_router", "max_throw_tech_router",
        "max_guard_crush_router", "max_airdash_rules_router", "max_wallbounce_router", "max_groundbounce_router",
        "max_otg_rules_router", "max_projectile_ecosystem_router", "max_assist_rules_router", "max_ai_easy_profile",
        "max_ai_normal_profile", "max_ai_hard_profile", "max_ai_boss_profile", "max_training_dummy_profile",
        "max_hitbox_debug_profile", "max_round_director_router", "max_pushback_router", "max_corner_escape_router",
        "max_tag_rules_router"
    })

    if feature_id in v23_ids:
        preset = get_preset(feature_id)
        if feature_id in {"required_action_library", "complete_gethit_library", "ffplus_air_template_bank"}:
            return _v23_required_air(feature_id, preset)
        if feature_id.endswith("_docs") or feature_id in {"win_quote_bank"}:
            return _v23_docs_package(feature_id, preset)
        return _v23_system_package(feature_id, preset)

    if feature_id in v25_ids:
        preset = get_preset(feature_id)
        if feature_id in _V25_DOC_IDS:
            return _v25_docs_package(feature_id, preset)
        if feature_id in _V25_MOVE_SPECS:
            pkg = _pack_from_specs(feature_id, preset.name, [_V25_MOVE_SPECS[feature_id]], list(preset.beginner_notes))
            if feature_id.startswith("max_ex_"):
                pkg.notes.append("EX starter: add meter spend/tuning after testing. The Max Meter Rules Router can centralize that logic.")
            if feature_id in {"max_level2_super", "max_cinematic_finisher", "max_boss_desperation"}:
                pkg.cns_block += _wrap(feature_id + "_super_notes", preset.name + " super pause notes", "[State -2, Factory Max super tuning note]\ntype = Null\ntrigger1 = 1\n; Copy SuperPause/EnvShake/PalFX into the generated state after testing timing.\n")
            return pkg
        return _v25_system_package(feature_id, preset)

    return None
